updated

diff --git a/shutdown b/shutdown
--- a/shutdown
+++ b/shutdown
@@ -1,43 +1,73 @@
 #!/bin/sh
+# shutdown - shutdown(8) lookalike for runit
 
-[ -r /etc/runit/runit.conf ] && . /etc/runit/runit.conf
-
-msg() {
-    echo -e "\e[0;32m*\e[0m $@"
+single() {
+  runsvchdir single
 }
 
-[ -x /etc/runit/shutdown.local ] && /etc/runit/shutdown.local
+abort() {
+  printf '%s\n' "$1" >&2
+  exit 1
+}
 
-msg "Saving random seed..."
-dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=512 2>/dev/null
+usage() {
+  abort "Usage: ${0##*/} [-fF] [-kchPr] time [warning message]"
+}
 
-if [ -n "$HARDWARECLOCK" ]; then
-    case "$HARDWARECLOCK" in
-		UTC)       CLOCKPARAMS="--utc" ;;
-		localtime) CLOCKPARAMS="--localtime" ;;
-	esac
-    msg "Setting up RTC to '${HARDWARECLOCK}'..."
-	hwclock --systohc "$CLOCKPARAMS"
+action=single
+
+while getopts akrhPHfFnct: opt; do
+  case "$opt" in
+    a|n|H) abort "'-$opt' is not implemented";;
+    t) ;;
+    f) touch /fastboot;;
+    F) touch /forcefsck;;
+    k) action=true;;
+    c) action=cancel;;
+    h|P) action=halt;;
+    r) action=reboot;;
+    [?]) usage;;
+  esac
+done
+shift $((OPTIND - 1))
+
+[ $# -eq 0 ] && usage
+
+time=$1; shift
+message="${*:-system is going down}"
+
+if [ "$action" = "cancel" ]; then
+  kill "$(cat /run/shutdown.pid)"
+  if [ -e /etc/nologin ] && ! [ -s /etc/nologin ]; then
+    rm /etc/nologin
+  fi
+  echo "${*:-shutdown cancelled}" | wall
+  exit
 fi
 
-msg "Sending TERM signal to processes..."
-pkill --inverse -s0,1 -TERM
-sleep 1
-msg "Sending KILL signal to processes..."
-pkill --inverse -s0,1 -KILL
+touch /run/shutdown.pid 2>/dev/null || abort "Not enough permissions to execute ${0#*/}"
+echo $$ >/run/shutdown.pid
 
-msg "Deactivating all swap files/partitions..."
-swapoff -a
+case "$time" in
+  now) time=0;;
+  +*) time=${time#+};;
+  *:*) abort "absolute time is not implemented";;
+  *) abort "invalid time";;
+esac
 
-msg "Bringing down the loopback interface..."
-ip link set lo down
-      
-msg "Unmounting all other currently mounted file systems..."
-umount --all --detach-loop --read-only \
-       --types notmpfs,nosysfs,nodevtmpfs,noproc,nodevpts >/dev/null
+for break in 5 0; do
+  [ "$time" -gt "$break" ] || continue
+  [ "$break" = 0 ] && touch /etc/nologin
 
-mount --options remount,ro /
+  printf '%s in %s minutes\n' "$message" "$time" | wall
+  printf 'shutdown: sleeping for %s minutes... ' "$(( time - break ))"
+  sleep $(( (time - break) * 60 ))
+  time="$break"
+  printf '\n'
 
-sync
+  [ "$break" = 0 ] && rm /etc/nologin
+done
 
-sleep 1
+printf '%s NOW\n' "$message" | wall
+
+$action
